version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: maybeworks
      MYSQL_DATABASE: maybeworks
      MYSQL_USER: maybeworks
      MYSQL_PASSWORD: maybeworks
